/**
 * DisclaimerPage — “not legal advice” disclosure for TrackSign reports.
 *
 * Route: /disclaimer
 * Dependencies: Navbar, Footer
 */

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const DisclaimerPage = () => {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 pb-20 pt-28">
        {/* TODO [BACKEND]: Have a lawyer review */}
        <p className="mb-4 text-xs" style={{ color: "#666" }}>
          Last updated: August 2026
        </p>
        <h1 className="mb-4 text-3xl font-semibold">Not legal advice</h1>
        <p className="text-sm leading-relaxed" style={{ color: "#999" }}>
          TrackSign is a software tool that uses artificial intelligence to analyze contract text and flag terms that may be risky, unfair, or unusual for freelancers and agencies.
        </p>
        <p className="mt-4 text-sm leading-relaxed" style={{ color: "#999" }}>
          TrackSign does not provide legal advice, legal opinions, or legal representation. It does not create an attorney-client relationship. The reports generated by TrackSign are informational only and are not a substitute for advice from a qualified lawyer.
        </p>
        <p className="mt-4 text-sm leading-relaxed" style={{ color: "#999" }}>
          You should always consult a licensed attorney before signing any contract, especially for high-value engagements or contracts with terms you do not fully understand.
        </p>
        <p className="mt-4 text-sm leading-relaxed" style={{ color: "#999" }}>
          TrackSign makes no warranties about the completeness or accuracy of its analysis. Contract language is complex and context-dependent. Our AI may miss relevant issues or flag terms that are standard in certain industries.
        </p>
        <p className="mt-4 text-sm leading-relaxed" style={{ color: "#999" }}>
          By using TrackSign, you acknowledge that you understand these limitations and that all decisions based on TrackSign reports are made at your own discretion and risk.
        </p>
      </main>
      <Footer />
    </>
  );
};

export default DisclaimerPage;
